### ISSUE TITLE
URLResource mentioned in docs does not exist

### ISSUE THREAD

**Issue by zmre** [oncue/knobs#11]
I'm not sure if the docs are previewing something yet to come or talking about something that is no longer with us, but the docs reference this resource:

    URLResource - loads any URI supported by the class java.net.URI.

Alas, though it sounds terrific, there is no URLResource that I can see.

**Comment by runarorama** [comment]
We should probably have a `UriResource` smart constructor like we have `FileResource`, but uriResource is definitely there. Try:

```
load(Resource(new URI("http://tempuri.org/my.cfg")).required)
```

**Comment by zmre** [comment]
I should have mentioned that I tried that already without success.  Here's the output:

```
scala> loadImmutable(Resource(new URI("http://tempuri.org/my.cfg")).required :: Nil)
res6: scalaz.concurrent.Task[knobs.Config] = scalaz.concurrent.Task@41be4666

scala> res6.run
java.lang.IllegalArgumentException: URI scheme is not "file"
  at java.io.File.<init>(File.java:421)
  at scala.io.Source$.fromFile(Source.scala:65)
  at knobs.Resource$$anon$2$$anonfun$load$2.apply(Resource.scala:201)
  at knobs.Resource$$anon$2$$anonfun$load$2.apply(Resource.scala:201)
  at scalaz.concurrent.Task$.Try(Task.scala:386)
  at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
  at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
  at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
  at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by runarorama** [comment]
https://github.com/oncue/knobs/pull/12

**Comment by zmre** [comment]
fast work, thanks @runarorama!
