### ISSUE TITLE
Can't run.

### ISSUE THREAD

**Issue by i-am-the-slime** [oncue/knobs#34]
I get this at runtime
```java
java.lang.NoSuchMethodError: scalaz.Free$.point(Lscala/Function0;)Lscalaz/Free;
java.lang.NoSuchMethodError: scalaz.Free$.point(Lscala/Function0;)Lscalaz/Free;
	at scalaparsers.Parsing$$anon$3$$anon$2.apply(ParsingUtil.scala:37)
	at scalaparsers.Parser$$anon$7$$anonfun$apply$4.apply(Parser.scala:59)
	at scalaparsers.Parser$$anon$7$$anonfun$apply$4.apply(Parser.scala:58)
	at scalaz.Free$$anonfun$resume$2.apply(Free.scala:107)
	at scalaz.Free$$anonfun$resume$2.apply(Free.scala:107)
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:77)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:239)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:239)
	at scalaz.Free.go2$1(Free.scala:150)
	at scalaz.Free.go(Free.scala:153)
	at scalaz.Free.run(Free.scala:239)
	at scalaparsers.Parser.run(Parser.scala:21)
	at knobs.ConfigParser$.runParser(Parser.scala:203)
	at knobs.ConfigParser$ParserOps.parse(Parser.scala:33)
	at knobs.Resource$$anonfun$loadFile$1$$anonfun$apply$2$$anonfun$apply$3.apply(Resource.scala:190)
	at knobs.Resource$$anonfun$loadFile$1$$anonfun$apply$2$$anonfun$apply$3.apply(Resource.scala:190)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:272)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:280)
	at scalaz.concurrent.Task$.Try(Task.scala:387)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:280)
	at scalaz.concurrent.Future.step(Future.scala:110)
	at scalaz.concurrent.Future.listen(Future.scala:75)
	at scalaz.concurrent.Future.runAsync(Future.scala:142)
	at scalaz.concurrent.Future.run(Future.scala:159)
	at scalaz.concurrent.Task.run(Task.scala:97)
```

I am suspecting a binary compatibility issue. Not sure, though.

Here are some more dependencies:
```scala

lazy val Http4sVersion = "0.15.0-SNAPSHOT"
lazy val CirceVersion   = "0.4.1"

libraryDependencies ++= Seq(
  "oncue.knobs"                %% "core"                 % "3.8.1",
  "io.circe"                   %% "circe-core"           % CirceVersion,
  "io.circe"                   %% "circe-generic"        % CirceVersion,
  "io.circe"                   %% "circe-parser"         % CirceVersion,
  "org.http4s"                 %% "http4s-dsl"           % Http4sVersion,
  "org.http4s"                 %% "http4s-circe"         % Http4sVersion,
  "org.http4s"                 %% "http4s-blaze-client"  % Http4sVersion
```

**Comment by i-am-the-slime** [comment]
Probably because `http4s` uses `scalaz-stream` version `0.8.2` and this uses `0.7.3a`

**Comment by i-am-the-slime** [comment]
It was a missing `a` in the dependency for `http4s`. Good.
